CREATE TABLE container_images (
    "ImageID" integer GENERATED BY DEFAULT AS IDENTITY,
    "BuildDate" timestamp with time zone NOT NULL,
    "RegistryType" integer NOT NULL,
    "Repository" character varying(255) NOT NULL,
    "RepositoryId" character varying(384) NOT NULL,
    "Status" integer NOT NULL,
    "Tag" character varying(128) NOT NULL,
    "Version" text NOT NULL,
    CONSTRAINT "PK_container_images" PRIMARY KEY ("ImageID")
);

CREATE UNIQUE INDEX "IX_container_images_RepositoryId" ON container_images ("RepositoryId");

CREATE UNIQUE INDEX "IX_container_images_ImageID_RepositoryId" ON container_images ("ImageID", "RepositoryId");

/*
USE Clutch;
CREATE TABLE container_images (
    ImageID INT AUTO_INCREMENT PRIMARY KEY,
    RepositoryId VARCHAR(384) NOT NULL UNIQUE,
    Repository VARCHAR(255) NOT NULL,
    Tag VARCHAR(128) NOT NULL,
    BuildDate DATETIME NOT NULL,
    RegistryType TINYINT NOT NULL,
    Status TINYINT NOT NULL DEFAULT 0,
    Version VARCHAR(255) NOT NULL,
    LastModified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    INDEX (RepositoryId)
);
*/