USE Clutch;
CREATE TABLE container_images (
    ImageID INT AUTO_INCREMENT PRIMARY KEY,
    RepositoryId VARCHAR(384) NOT NULL UNIQUE,
    Repository VARCHAR(255) NOT NULL,
    Tag VARCHAR(128) NOT NULL,
    BuildDate DATETIME NOT NULL,
    RegistryType TINYINT NOT NULL,
    Status TINYINT NOT NULL DEFAULT 0,
    Version VARCHAR(255) NOT NULL,
    LastModified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    INDEX (RepositoryId)
);