// <auto-generated />
using System;
using Clutch.API.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clutch.API.Migrations
{
    [DbContext(typeof(ContainerImageContext))]
    [Migration("20240806171954_container_images")]
    partial class container_images
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clutch.API.Models.Image.ContainerImageModel", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageID"));

                    b.Property<DateTime>("BuildDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistryType")
                        .HasColumnType("integer");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImageID");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.HasIndex("ImageID", "RepositoryId")
                        .IsUnique();

                    b.ToTable("container_images", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
