version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend-network
    container_name: redis-cache

  Clutch.api:
    image: ${DOCKER_REGISTRY-}clutchapi
    build:
      context: Clutch.API
      dockerfile: Dockerfile 
    ports:
      - 8080:80
    depends_on:
      - redis 
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
