services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend-network
    container_name: redis-cache

  Clutch.api:
    image: ${DOCKER_REGISTRY-}clutchapi
    build:
      context: ./Clutch.API
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../..
        target: /src 
    ports:
      - 8080:8080
      # MAC - 7102:8080 
    depends_on:
      - redis 
    networks:
      - backend-network
    env_file:
      - .env

networks:
  backend-network:
    driver: bridge
