name: Build and Push to ACR

on:
  workflow_dispatch:

env:
  REPOSITORY_NAME: lvlup-sw/clutchapi
  REPOSITORY_TAG: aspire-dev  

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: development
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: 'Docker Login'
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_CLIENTID }}
        password: ${{ secrets.REGISTRY_CLIENTSECRET }}

    - name: Build & Push Container
      run: |
        echo "Build image and push to ${{ vars.REGISTRY_LOGIN_SERVER }}"

        echo "Building the container..."
        docker build -t ${{ env.REPOSITORY_NAME }}:${{ env.REPOSITORY_TAG }} .
        echo

        echo "Tagging for ACR..."
        docker tag ${{ env.REPOSITORY_NAME }}:${{ env.REPOSITORY_TAG }} ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{ env.REPOSITORY_TAG }}
        echo

        echo "Push image to ACR"
        docker push ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{ env.REPOSITORY_TAG }}
        echo